--Archivo de creación de BD ventas de inmuebles
--Fecha de creación: 18/05/2025
--Creado por: Natalia Bernal & Mileth Martinez
--Modificado por:
--Fecha de modificación:
--Observación:

/*
Dataset utilizado: Real Estate Sales 2001–2022
Fuente: https://www.kaggle.com/datasets/omniamahmoudsaeed/real-estate-sales-2001-2022
*/

-- EJECUTAR COMO USUARIO SYSTEM

-- Crear tablespaces para las tablas la BD de venta de inmuebles
CREATE TABLESPACE DATOS_VENTAS
    DATAFILE '/datos_ventas.dbf' SIZE 10M
    AUTOEXTEND ON NEXT 10M MAXSIZE 50M;

-- Crear tablespaces para los indices la BD de venta de inmuebles
CREATE TABLESPACE TS_INDICES_VENTAS
    DATAFILE '/indices_ventas.dbf' SIZE 10M
    AUTOEXTEND ON NEXT 10M MAXSIZE 50M;

-- Crear usuario de prueba para la BD de venta de inmuebles
CREATE USER USER_PRUEBA
    DEFAULT TABLESPACE DATOS_VENTAS
    TEMPORARY TABLESPACE TEMP
    PROFILE DEFAULT
IDENTIFIED BY ABC987;
 
-- Asignar permisos al usuario de prueba
GRANT
    CREATE SESSION,
    CREATE TABLE,
    CREATE SEQUENCE,
    INSERT ANY TABLE,
    CREATE PROCEDURE
TO USER_PRUEBA;

-- Asignar cuota de espacio
ALTER USER USER_PRUEBA
    QUOTA UNLIMITED ON DATOS_VENTAS;

ALTER USER USER_PRUEBA
    QUOTA UNLIMITED ON TS_INDICES_VENTAS;

-- Conectar como USER_PRUEBA
CONN USER_PRUEBA/ABC987;

-- Crear secuencia para el id de pueblo
CREATE SEQUENCE SEQ_PUEBLO_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Crear secuencia para el id de tipo de propiedad
CREATE SEQUENCE SEQ_TIPO_PROPIEDAD_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Crear secuencia para el id de tipo de residencia
CREATE SEQUENCE SEQ_TIPO_RESIDENCIA_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Crear secuencia para el id de localizacion
CREATE SEQUENCE SEQ_LOCALIZACIONES_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Crear secuencia para el id de observaciones
CREATE SEQUENCE SEQ_OBSERVACIONES_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Crear secuencia para el id de ventas
CREATE SEQUENCE SEQ_VENTAS_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Crear secuencia para el id de propiedades
CREATE SEQUENCE SEQ_PROPIEDAD_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Crear tabla de pueblos
CREATE TABLE PUEBLOS (
    ID_PUEBLO NUMBER DEFAULT SEQ_PUEBLO_ID.NEXTVAL,
    NOMBRE    VARCHAR2(70)
)
TABLESPACE DATOS_VENTAS;

-- Comentarios de la tabla pueblos
COMMENT ON TABLE PUEBLOS IS
    'Lista de pueblos o ciudades de EE.UU. donde se ubican propiedades.';

COMMENT ON COLUMN PUEBLOS.ID_PUEBLO IS
    'Identificador único del pueblo.';

COMMENT ON COLUMN PUEBLOS.NOMBRE IS
    'Nombre del pueblo o ciudad.';

-- Crear tabla de tipos de propiedad
CREATE TABLE TIPOS_PROPIEDAD (
    ID_TIPO_PROPIEDAD NUMBER DEFAULT SEQ_TIPO_PROPIEDAD_ID.NEXTVAL,
    DESCRIPCION       VARCHAR2(50)
)
TABLESPACE DATOS_VENTAS;

-- Comentarios de la tabla tipos de propiedad
COMMENT ON TABLE TIPOS_PROPIEDAD IS
    'Tipos generales de propiedad (ej. Comercial, Residencial).';

COMMENT ON COLUMN TIPOS_PROPIEDAD.ID_TIPO_PROPIEDAD IS
    'Identificador único del tipo de propiedad.';

COMMENT ON COLUMN TIPOS_PROPIEDAD.DESCRIPCION IS
    'Descripción del tipo de propiedad.';

-- Crear tabla de tipos de residencia
CREATE TABLE TIPOS_RESIDENCIA (
    ID_TIPO_RESIDENCIA NUMBER DEFAULT SEQ_TIPO_RESIDENCIA_ID.NEXTVAL,
    DESCRIPCION        VARCHAR2(50)
)
TABLESPACE DATOS_VENTAS;

-- Comentarios de la tabla tipos de residencia
COMMENT ON TABLE TIPOS_RESIDENCIA IS
    'Clasificación del tipo de residencia (ej. Unifamiliar, Multifamiliar).';

COMMENT ON COLUMN TIPOS_RESIDENCIA.ID_TIPO_RESIDENCIA IS
    'Identificador único del tipo de residencia.';

COMMENT ON COLUMN TIPOS_RESIDENCIA.DESCRIPCION IS
    'Descripción del tipo de residencia.';

-- Crear tabla de ubicaciones
CREATE TABLE LOCALIZACIONES (
    ID_LOCALIZACION NUMBER DEFAULT SEQ_LOCALIZACIONES_ID.NEXTVAL,
    ID_PUEBLO       NUMBER NOT NULL,
    LATITUD         NUMBER,
    LONGITUD        NUMBER,
    DIRECCION       VARCHAR2(100)
)
TABLESPACE DATOS_VENTAS;

-- Comentarios de la tabla localizaciones
COMMENT ON TABLE LOCALIZACIONES IS
    'Ubicaciones de las propiedades';

COMMENT ON TABLE LOCALIZACIONES IS
    'Información geográfica y dirección específica de cada propiedad.';

COMMENT ON COLUMN LOCALIZACIONES.ID_LOCALIZACION IS
    'Identificador único de la localización.';

COMMENT ON COLUMN LOCALIZACIONES.ID_PUEBLO IS
    'Llave foránea al pueblo correspondiente.';

COMMENT ON COLUMN LOCALIZACIONES.LATITUD IS
    'Coordenada geográfica de latitud.';

COMMENT ON COLUMN LOCALIZACIONES.LONGITUD IS
    'Coordenada geográfica de longitud.';

COMMENT ON COLUMN LOCALIZACIONES.DIRECCION IS
    'Dirección textual de la propiedad.';

-- Crear tabla de propiedades
CREATE TABLE PROPIEDADES (
    ID_PROPIEDAD       NUMBER DEFAULT SEQ_PROPIEDAD_ID.NEXTVAL,
    NUMERO_SERIAL      NUMBER NOT NULL,
    ID_TIPO_PROPIEDAD  NUMBER,
    ID_TIPO_RESIDENCIA NUMBER,
    ID_LOCALIZACION    NUMBER,
    VALOR_CATASTRAL    FLOAT
)
TABLESPACE DATOS_VENTAS;

-- Comentarios de la tabla propiedades
COMMENT ON TABLE PROPIEDADES IS
    'Propiedades inmobiliarias registradas en la base de datos.';

COMMENT ON COLUMN PROPIEDADES.ID_PROPIEDAD IS
    'Identificador único de la propiedad.';

COMMENT ON COLUMN PROPIEDADES.NUMERO_SERIAL IS
    'Número de serie de la propiedad';

COMMENT ON COLUMN PROPIEDADES.ID_TIPO_PROPIEDAD IS
    'Tipo general de propiedad.';

COMMENT ON COLUMN PROPIEDADES.ID_TIPO_RESIDENCIA IS
    'Tipo de residencia, si aplica.';

COMMENT ON COLUMN PROPIEDADES.ID_LOCALIZACION IS
    'Ubicación asociada a la propiedad.';

COMMENT ON COLUMN PROPIEDADES.VALOR_CATASTRAL IS
    'Valor fiscal de la propiedad.';

CREATE TABLE VENTAS (
    ID_VENTA       NUMBER DEFAULT SEQ_VENTAS_ID.NEXTVAL,
    ID_PROPIEDAD  NUMBER NOT NULL,
    ANIO_VENTA     NUMBER NOT NULL,
    FECHA_REGISTRO DATE NOT NULL,
    VALOR_VENTA    FLOAT,
    RELACION_VENTA FLOAT,
    CODIGO_NO_USO  VARCHAR2(50)
)
TABLESPACE DATOS_VENTAS;

-- Comentarios de la tabla ventas
COMMENT ON TABLE VENTAS IS
    'Ventas de propiedades';

COMMENT ON COLUMN VENTAS.ID_VENTA IS
    'Identificador de venta';

COMMENT ON COLUMN VENTAS.ID_PROPIEDAD IS
    'Identificador de la propiedade propiedad';

COMMENT ON COLUMN VENTAS.ANIO_VENTA IS
    'Año de la venta';

COMMENT ON COLUMN VENTAS.FECHA_REGISTRO IS
    'Fecha de registro de la venta';

COMMENT ON COLUMN VENTAS.VALOR_VENTA IS
    'Valor de la venta';

COMMENT ON COLUMN VENTAS.RELACION_VENTA IS
    'Relacion de la venta';

COMMENT ON COLUMN VENTAS.CODIGO_NO_USO IS
    'Codigo de no uso de la venta';

-- Crear tabla de observaciones
CREATE TABLE OBSERVACIONES (
    ID_OBSERVACION NUMBER DEFAULT SEQ_OBSERVACIONES_ID.NEXTVAL,
    ID_VENTA       NUMBER NOT NULL,
    NOTA           VARCHAR2(130) NOT NULL,
    TIPO_ORIGEN    CHAR(3) NOT NULL
)
TABLESPACE DATOS_VENTAS;

-- Comentarios de la tabla observaciones
COMMENT ON TABLE OBSERVACIONES IS
    'Observaciones registradas sobre una venta específica.';

COMMENT ON COLUMN OBSERVACIONES.ID_OBSERVACION IS
    'Identificador único de la observación.';

COMMENT ON COLUMN OBSERVACIONES.ID_VENTA IS
    'Venta a la que pertenece esta observación.';

COMMENT ON COLUMN OBSERVACIONES.NOTA IS
    'Contenido textual de la observación.';

COMMENT ON COLUMN OBSERVACIONES.TIPO_ORIGEN IS
    'Tipo de origen de la observacion(ASE = Asesor de Ventas, OPM = Office of Policy and Management)';

-- Crear restricciones de la tabla PUEBLOS
ALTER TABLE PUEBLOS
    ADD CONSTRAINT PK_PUEBLOS PRIMARY KEY ( ID_PUEBLO )
        USING INDEX TABLESPACE TS_INDICES_VENTAS;

ALTER TABLE PUEBLOS ADD CONSTRAINT UC_PUEBLO_NOMBRE UNIQUE ( NOMBRE );

-- Crear restricciones de la tabla TIPO_PROPIEDAD
ALTER TABLE TIPOS_PROPIEDAD
    ADD CONSTRAINT PK_TIPO_PROPIEDAD PRIMARY KEY ( ID_TIPO_PROPIEDAD )
        USING INDEX TABLESPACE TS_INDICES_VENTAS;

-- Crear restricciones de la tabla TIPO_RESIDENCIA
ALTER TABLE TIPOS_RESIDENCIA
    ADD CONSTRAINT PK_TIPO_RESIDENCIA PRIMARY KEY ( ID_TIPO_RESIDENCIA )
        USING INDEX TABLESPACE TS_INDICES_VENTAS;

-- Crear restricciones de la tabla LOCALIZACIONES
ALTER TABLE LOCALIZACIONES
    ADD CONSTRAINT PK_LOCALIZACIONES PRIMARY KEY ( ID_LOCALIZACION )
        USING INDEX TABLESPACE TS_INDICES_VENTAS;

ALTER TABLE LOCALIZACIONES
    ADD CONSTRAINT FK_LOCALIZACIONES_PUEBLO FOREIGN KEY ( ID_PUEBLO )
        REFERENCES PUEBLOS ( ID_PUEBLO );

-- Crear restricciones de la tabla PROPIEDADES
ALTER TABLE PROPIEDADES
    ADD CONSTRAINT PK_PROPIEDADES PRIMARY KEY ( ID_PROPIEDAD )
        USING INDEX TABLESPACE TS_INDICES_VENTAS;

ALTER TABLE PROPIEDADES
    ADD CONSTRAINT FK_PROPIEDADES_TIPO_PROPIEDAD FOREIGN KEY ( ID_TIPO_PROPIEDAD )
        REFERENCES TIPOS_PROPIEDAD ( ID_TIPO_PROPIEDAD );

ALTER TABLE PROPIEDADES
    ADD CONSTRAINT FK_PROPIEDADES_TIPO_RESIDENCIA FOREIGN KEY ( ID_TIPO_RESIDENCIA )
        REFERENCES TIPOS_RESIDENCIA ( ID_TIPO_RESIDENCIA );

ALTER TABLE PROPIEDADES
    ADD CONSTRAINT FK_PROPIEDADES_LOCALIZACION FOREIGN KEY ( ID_LOCALIZACION )
        REFERENCES LOCALIZACIONES ( ID_LOCALIZACION );

-- Crear restricciones de la tabla VENTAS
ALTER TABLE VENTAS
    ADD CONSTRAINT PK_VENTAS PRIMARY KEY ( ID_VENTA )
        USING INDEX TABLESPACE TS_INDICES_VENTAS;

ALTER TABLE VENTAS
    ADD CONSTRAINT FK_VENTAS_PROPIEDAD FOREIGN KEY ( ID_PROPIEDAD )
        REFERENCES PROPIEDADES ( ID_PROPIEDAD );

-- Crear restricciones de la tabla OBSERVACIONES
ALTER TABLE OBSERVACIONES
    ADD CONSTRAINT PK_OBSERVACIONES PRIMARY KEY ( ID_OBSERVACION )
        USING INDEX TABLESPACE TS_INDICES_VENTAS;

ALTER TABLE OBSERVACIONES
    ADD CONSTRAINT FK_OBSERVACIONES_VENTAS FOREIGN KEY ( ID_VENTA )
        REFERENCES VENTAS ( ID_VENTA );

ALTER TABLE OBSERVACIONES
    ADD CONSTRAINT CK_OBSERVACIONES_TIPO_ORIGEN CHECK ( TIPO_ORIGEN IN ( 'ASE', 'OPM' ) );